codeshare/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^(?P<course_name>[^/]+)/$', views.course, name='course'),
    url(r'^(?P<course_name>[^/]+)/changeaccess/$',
        views.changeCourseAccess, name='changeaccess'),
    url(r'^(?P<course_name>[^/]+)/(?P<snippet_id>[0-9]+)/delete/$',
        views.delete, name='delete'),
]

django_project/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('codeshare.urls', namespace='codeshare')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

codeshare/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User


class Instructor(models.Model):
    user = models.OneToOneField(User)

    def __unicode__(self):
        return self.user.username

    def __str__(self):
        return self.user.username


class Course(models.Model):
    name = models.CharField(max_length=30)
    creator = models.ForeignKey(User, null=True)
    isPrivate = models.BooleanField(default=False)

    def __unicode__(self):
        return str(self.name)

    def __str__(self):
        return str(self.name)


class CodeSnippet(models.Model):
    course = models.ForeignKey(Course)
    title = models.CharField(null=True,
                             max_length=30,
                             blank=True)
    code = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.title + " | " + str(self.timestamp)

    def __str__(self):
        return self.title + " | " + str(self.timestamp)


class CourseAccess(models.Model):
    access = models.BooleanField()

codeshare/forms.py
from django import forms

from django.forms import TextInput, Textarea
from django.contrib.auth.models import User

from .models import Instructor, CodeSnippet


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'name': 'password', 'placeholder': 'Password'}))

    class Meta:
        model = User
        fields = [
            "username",
            "password",
        ]
        widgets = {
            "username": TextInput(attrs={'class': 'form-control', 'name': 'username', 'placeholder': 'Username'}),
        }


class InstructorForm(forms.ModelForm):

    class Meta:
        model = Instructor
        fields = []


class SnippetForm(forms.ModelForm):

    class Meta:
        model = CodeSnippet
        fields = [
            "title",
            "code",
        ]
        widgets = {
            "title": TextInput(attrs={'class': 'form-control', 'placeholder': 'Title (not required)'}),
            "code": Textarea(attrs={'class': 'form-control', 'placeholder': 'Enter code here'}),
        }

codeshare/views.py
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.contrib import auth
from django.contrib.auth import authenticate
from django.views.decorators.csrf import ensure_csrf_cookie

from rest_framework.decorators import api_view

from serializers import CourseAccessSerializer
from .models import User, Course, CodeSnippet, Instructor
from .forms import SnippetForm, UserForm, InstructorForm


def index(request):
    if request.POST:
        course_name = request.POST.get("course_name").title()
        if course_name:
            if not doesCourseExist(course_name):
                addCourse(request, course_name)

            return HttpResponseRedirect(reverse("codeshare:course", kwargs={"course_name": course_name}))

    return render(request, "codeshare/index.html")


def getCourseFromName(course_name):
    for course in Course.objects.all():
        if course.name == course_name:
            return course


def addSnippet(form, course_name):
    newSnippet = CodeSnippet()
    newSnippet.course = getCourseFromName(course_name)
    newSnippet.title = form.cleaned_data["title"] \
        if form.cleaned_data["title"] else "Code Snippet"
    newSnippet.code = form.cleaned_data["code"]
    newSnippet.save()


def getCourseSnippets(course_name):
    return CodeSnippet.objects.filter(course=getCourseFromName(course_name))


def addCourse(request, course_name):
    newCourse = Course(name=course_name)
    try:
        newCourse.creator = User.objects.get(username=request.user.username)
    except:
        newCourse.creator = User.objects.get(username='admin')
    newCourse.save()


def doesCourseExist(course_name):
    return course_name in list(Course.objects.all().values_list("name", flat=True))


def isCourseCreator(request, course_name):
    course = getCourseFromName(course_name)
    try:
        if course.creator == User.objects.get(username=request.user.username):
            return True
    except:
        return False


def getCourseAccess(course_name):
    course = getCourseFromName(course_name)
    return course.isPrivate


def course(request, course_name):
    course_name = course_name.title()
    if not doesCourseExist(course_name):
        addCourse(request, course_name)

    if request.POST:
        form = SnippetForm(request.POST)
        if form.is_valid():
            addSnippet(form, course_name)

    context = {
        "course_name": course_name,
        "form": SnippetForm(),
        "snippets": getCourseSnippets(course_name),
        "is_creator": isCourseCreator(request, course_name),
        "is_private": getCourseAccess(course_name),
    }

    return render(request, "codeshare/course_website.html", context)


def delete(request, course_name, snippet_id):
    obj = get_object_or_404(CodeSnippet,
                            pk=snippet_id,
                            course=getCourseFromName(course_name))
    obj.delete()

    return HttpResponseRedirect(reverse("codeshare:course", kwargs={"course_name": course_name}))


def login(request):
    if request.POST:
        if 'login' in request.POST:
            return loginUser(request)
        elif 'register' in request.POST:
            return register(request)

    context = {
        "user_form": UserForm(),
        "instructor_form": InstructorForm(),
    }

    return render(request, "codeshare/login.html", context)


def loginUser(request):
    username = request.POST['username']
    password = request.POST['password']

    print ("Attempting login for %s" % username)

    user = authenticate(username=username, password=password)
    if user:
        if user.is_active:
            auth.login(request, user)
            print ("Login successful")
            return HttpResponseRedirect(reverse("codeshare:index"))
        else:
            return HttpResponseRedirect("Your account is disabled!")
    else:
        return HttpResponse("Invalid login details")


def register(request):
    try:
        if User.objects.get(username=request.POST['username']):
            return HttpResponse("Username already taken")
    except:
        user_form = UserForm(request.POST)
        if user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            instructor_form = InstructorForm(
                request.POST, instance=Instructor(user=user))
            if instructor_form.is_valid():
                instructor = instructor_form.save(commit=False)
                instructor.user = user
                instructor.save()

            print ("Registeration successful")
            auth.login(request, user)
            return HttpResponseRedirect(reverse("codeshare:index"))


def logout(request):
    print ("Signing off...")
    auth.logout(request)
    return HttpResponseRedirect(reverse("codeshare:index"))


@api_view(['POST'])
@ensure_csrf_cookie
def changeCourseAccess(request, course_name):
    course_name = course_name.title()
    serializer = CourseAccessSerializer(data=request.data)
    if serializer.is_valid():
        if isCourseCreator(request, course_name):
            access = True if request.POST['access'] == 'true' else False
            course = getCourseFromName(course_name)
            course.isPrivate = access
            course.save()
            return JsonResponse({
                "detail": "Course access changed successfully"
            })
        else:
            return JsonResponse({
                "detail": "You do not have appropriate permissions"
            })

django_project/templates/codeshare/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Course Codeshare</title>

    <!-- STYLESHEETS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
          crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
          integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp"
          crossorigin="anonymous">
</head>
<body>
<div class="container">
    {% block content %}

    {% endblock content %}
</div>

<footer>
    Made with <span title="peanuts">🥜</span> by <a href="https://github.com/ymittal">Yash</a>
</footer>

<!-- SCRIPTS -->
<script type="text/javascript" src="http://code.jquery.com/jquery-3.1.1.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"></script>

</body>
</html>

django_project/templates/codeshare/course_website.html
{% extends "codeshare/base.html" %}

{% block content %}

{% load static %}
<link rel="stylesheet" href="{% static 'css/base.css' %}">
<link rel="stylesheet" href="{% static 'css/coursepage.css' %}">

<h1 id="course-title">
    {{ course_name }}
</h1>

{% if is_creator %}
    <div class="checkbox">
        <label>
            <!-- TODO: onclick listener on checkbox to change course access -->
            <input type="checkbox" class="accesscheckbox" onclick="changeCourseAccess()" {% if is_private %} checked {% endif %}>
            Don't allow others to modify my codeshare
        </label>
    </div>
{% endif %}

{% if is_creator or not is_private %}
    <div class="add-section">
        <form action="" method="POST">
        {% csrf_token %}

        {{ form.errors }}
        {{ form.non_field_errors }}

        <div class="form-group">
            <div class="input-group col-xs-4">
                {{ form.title }}
            </div>
        </div>
        <div class="form-group">
            <div class="input-group col-xs-8">
                {{ form.code }}
            </div>
        </div>
        <div class="form-group">
            <div class="input-group col-xs-2">
                <input class="btn btn-primary" type="submit" value="Add Snippet"/>
            </div>
        </div>

        </form>
    </div>

    <hr>
{% endif %}

<div class="list-section">
    {% if snippets %}
    <ul>
        {% for snippet in snippets reversed %}
        <div class="snippet">
            <div class="clearfix">
                <span class="btn-group pull-right">
                    <button class="btn btn-success btn-copy" data-clipboard-target="#s{{ snippet.id }}">Copy</button>
                    {% if is_creator or not is_private %}
                        <a class="btn btn-danger" href="{% url 'codeshare:delete' course_name=course_name snippet_id=snippet.id %}">Delete</a>
                    {% endif %}
                </span>
                <span class="inline">
                    <h4 class="title">{{ snippet.title }}</h4>
                </span>
            </div>
            <div id="s{{ snippet.id }}">
                <pre><code class="prettyprint">{{ snippet.code }}</code></pre>
            </div>

            {% if not forloop.last %}
                <hr>
            {% endif %}
        </div>

        {% endfor %}
    </ul>
    {% else %}
        <div id="snippet-empty">
            No snippets found.
        </div>
    {% endif %}
</div>

<!-- SCRIPTS -->
<script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js"></script>
<script src="{% static 'js/clipboard.min.js' %}"></script>
<script>
    var clipboard = new Clipboard('.btn-copy');

    function changeCourseAccess() {
        var isPrivate = $('.accesscheckbox:checked').val() ? true : false
        console.log(isPrivate)

        $.post("changeaccess/", {
                csrfmiddlewaretoken: '{{csrf_token}}',
                access: isPrivate
            },
            function(data, status) {
                console.log(data, status)
            })
    }
</script>

{% endblock content %}

django_project/templates/codeshare/index.html
{% extends "codeshare/base.html" %}

{% block content %}

{% load static %}
<link rel="stylesheet" href="{% static 'css/base.css' %}">
<link rel="stylesheet" href="{% static 'css/home.css' %}">

<div class="main-content">
	<div class="panel panel-default course-panel">
	  <div class="panel-heading">Codeshare</div>
		<div class="panel-body">
			<form action="" method="post">
				{% csrf_token %}

				<div class="clearfix">
					<div class="input-group img-rounded pull-left">
						<input class="form-control" placeholder="Course or workshop name" id="course" type="text" name="course_name" autocomplete="off">
					</div>
					<div class="input-group pull-right">
						<input class="btn btn-success" type="submit" value="Submit"/>
					</div>
				</div>
			</form>
		</div>
	</div>

	<div class="login-status">
		{% if request.user.is_authenticated %}
			(<strong>{{ request.user.username }}</strong> logged in)
			<a href="logout">Logout</a>
		{% else %}
			Are you a professor? <a href="login">Login</a>
		{% endif %}
	</div>
</div>

{% endblock content %}

django_project/templates/codeshare/login.html
{% extends "codeshare/base.html" %}

{% block content %}

{% load static %}
<link rel="stylesheet" href="{% static 'css/base.css' %}">
<link rel="stylesheet" href="{% static 'css/login.css' %}">

<div class="main-content">
	<form action="" method="post" class="form-horizontal">
		{% csrf_token %}

		<div class="form-group">
			<div class="col-sm-4">
				{{ user_form.username }}
			</div>
		</div>
		<div class="form-group">
			<div class="col-sm-4">
				{{ user_form.password }}
			</div>
		</div>
		<div class="btn-group">
			<div class="form-group pull-left">
				<div class="col-xs-2">
					<input class="btn btn-default" type="submit" name="login" value="Login">
				</div>
			</div>
			&nbsp;
			<div class="form-group pull-right">
				<div class="col-xs-2">
					<input class="btn btn-default" type="submit" name="register" value="Register">
				</div>
			</div>
		</div>
	</form>
</div>

{% endblock content %}